# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e3d2d696fb3cd4bb9cd2107d679ed5b380dc4eab265af969fd213e9ff157e26d025feccb694e196a066f537cabcf5c8beec861d43acd1d5d0e3b81845a04597

test:
  secret_key_base: 3e1e693c8a6a6d2cdae26ca77ce166a9ad0fdc6062d0f835e3ddbbf73d67ff088441d3758be2152f853a87905659948d498be30bf9421ede7c6efae9bb1e1737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
